export const Icon = {
  contect: require('../assets/contect.png'),
  videocamera: require('../assets/videocamera.png'),
  video: require('../assets/video.png'),
  gallery: require('../assets/gallery.png'),
  back: require('../assets/back.png'),
  back10sec: require('../assets/back10sec.png'),
  camera: require('../assets/camera.png'),
  cancel: require('../assets/cancel.png'),
  fullscreen: require('../assets/fullscreen.png'),
  logo: require('../assets/logo.png'),
  minimize: require('../assets/minimize.png'),
  mute: require('../assets/mute.png'),
  off: require('../assets/off.png'),
  pause: require('../assets/pause.png'),
  profile: require('../assets/profile.png'),
  resume: require('../assets/resume.png'),
  scroll: require('../assets/scroll.png'),
  send: require('../assets/send.png'),
  skip10sec: require('../assets/skip10sec.png'),
  true: require('../assets/true.png'),
  unmute: require('../assets/unmute.png'),
  search: require('../assets/search.png'),
  download: require('../assets/download.png'),
  group: require('../assets/group.png'),
  menu: require('../assets/menu.png'),
  theme: require('../assets/theme.png'),
};
